server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.multitenantpoc: DEBUG

# Configuraci√≥n custom de tenants (para el RoutingDataSource)
tenants:
  datasources:
    tenant_a:
      url: jdbc:mysql://localhost:3306/tenant_a_db?useSSL=false&serverTimezone=UTC
      username: root
      password: mypassword

    tenant_b:
      url: jdbc:mysql://localhost:3306/tenant_b_db?useSSL=false&serverTimezone=UTC
      username: root
      password: mypassword
